plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '1.0.21'
}

repositories {
    mavenLocal()
    maven { url = uri('https://maven.aliyun.com/repository/public') }
    maven { url = uri('https://maven.aliyun.com/repository/central') }
    mavenCentral()
    maven { url = uri('https://maven.neoforged.net/releases') }
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id
}

// 将 gradle.properties 中的 mod_version 展开到 neoforge.mods.toml 的 ${mod_version} 占位符
tasks.named('processResources') {
    inputs.property 'version', mod_version
    filesMatching('META-INF/neoforge.mods.toml') {
        expand 'mod_version': mod_version
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test) {
    useJUnitPlatform()
}
