plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '1.0.21'
}

repositories {
    mavenLocal()
    maven { url = uri('https://maven.aliyun.com/repository/public') }
    maven { url = uri('https://maven.aliyun.com/repository/central') }
    mavenCentral()
    maven { url = uri('https://maven.neoforged.net/releases') }
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}
