pluginManagement {
    repositories {
        mavenLocal()
        maven { url = uri('https://maven.aliyun.com/repository/public') }
        maven { url = uri('https://maven.aliyun.com/repository/gradle-plugin') }
        maven { url = uri('https://maven.aliyun.com/repository/central') }
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri('https://maven.neoforged.net/releases') }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        maven { url = uri('https://maven.aliyun.com/repository/public') }
        maven { url = uri('https://maven.aliyun.com/repository/central') }
        maven { url = uri('https://maven.aliyun.com/repository/gradle-plugin') }
        mavenCentral()
        maven { url = uri('https://maven.neoforged.net/releases') }
    }
}

rootProject.name = 'smarthorde'
